language: java
jdk:
- oraclejdk8
branches:
  only:
  - master
  - develop
notifications:
  email:
    recipients:
    - adrian.rodriguz.caballero@alumnos.upm.es
services:
- mysql
before_install:
- mysql -e 'CREATE DATABASE IF NOT EXISTS forge;'
script:
- mvn verify --settings settings.xml
- mvn org.jacoco:jacoco-maven-plugin:prepare-agent verify --settings settings.xml
- mvn sonar:sonar -Dsonar.organization=cijaraadrian-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR --settings settings.xml
